# Generated by Django 3.0.7 on 2020-07-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
